Server closed the connection: [Errno 103] Software caused connection abort
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 1 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 2 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 3 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 4 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 5 at connecting failed: OSError: [Errno 101] Network is unreachable
Attempt 6 at connecting failed: OSError: [Errno 101] Network is unreachable
Automatic reconnection failed 5 time(s)
游뱄 Bot WebP aktif... Menunggu sinyal dari channel...
游닌 Detected: SELL
游닌 Detected: SELL
游닌 Detected: BUY
游닌 Detected: BUY
游닌 Detected: BUY
游닌 Detected: BUY
游닌 Detected: BUY
游닌 Detected: BUY
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/bot_autorun/bot_stiker_vip.py", line 31, in <module>
    client.run_until_disconnected()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/updates.py", line 96, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/telethon/client/updates.py", line 486, in _keepalive_loop
    await asyncio.wait_for(
  File "/data/data/com.termux/files/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
ConnectionError: Connection to Telegram failed 5 time(s)
